name: Auto-Label
on:
  issues:
    types: [opened]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            const {repo, owner, number} = context.issue;
            await github.rest.issues.addLabels({repo, owner, issue_number: number, labels: ['unconfirmed']});
